### ISSUE TITLE
Small question about the using UpdateArg1 function

### ISSUE THREAD

**Issue by ruihai0925** [AMReX-Codes/IAMR#13]
Hello all,

I have a small question about the UpdateArg1, see here: https://github.com/AMReX-Codes/IAMR/blob/29f74453b9ef0bb4c69db43354887a840cbc6fa4/Source/Projection.cpp#L1636 ,
it is used to update the pressure after doing the synchronization projection in the initial step. But for updating the pressure, I think the equation is Pnew = Pnew + Pold, not Pnew = Pnew + Pold/dt, according to formulas in the JCP paper. So the input parameter should not be 1.0/dt. **I am not sure whether it is a bug here or I missed some important things.**

Thanks for someone's suggestion and comments.

**Comment by ajnonaka** [comment]
Maybe there is a factor of dt hidden somewhere in the code I haven't spotted yet, but I think I agree with you.  This is the initial sync projection (composite over all levels) to compute the initial pressure.  The quantity we are projecting is Vproj=(unew-uold)/dt.  Thus the pressure increment should be pnew = pold + phi, where phi is the solution to the elliptic problem.  @asalmgren do you agree?  I am going offline for a few hours but can do some numerical tests to confirm later.  Basically what you want to do it set "ns.init_iter" to a very large number and see if the pressure converges to something.  Try it with "1/dt" and "1" in the UpdateArg1 weighting and see if anything interesting happens.

**Comment by WeiqunZhang** [comment]
dt = 1

**Comment by ruihai0925** [comment]
Aaha, I really apologize for asking this stupid question. But indeed I have not found it before. The dt is an input parameter, which equals to 1. I should be more careful next time.

Thanks, everyone.

**Comment by ajnonaka** [comment]
Doh!  The use of "dt" as the input parameter name is a bit misleading.  I'll change it to "factor".
