### ISSUE TITLE
AMReX CUDA Isssue with CUDA version 11.2/11.3/11.6/11.7

### ISSUE THREAD

**Issue by nishaag** [AMReX-Codes/IAMR#151]
I built the AMReX/amrex/Tests/GPU/Vector code for NVIDIA A100 GPU with the command make CUDA_ARCH=80, it built successfully but threw the below error at runtime. I tried  with the CUDA version 11.2/11.3/11.6/11.7 but everytime facing the same issue , Please help in this regard

---------------------------------------------------------------------

[/AMReX/amrex/Tests/GPU/Vector]$ ./main3d.gnu.CUDA.ex inputs
Initializing CUDA...
CUDA initialized with 1 device.
amrex::Abort::0::GPU last error detected in file ../../..//Src/Base/AMReX_GpuLaunchFunctsG.H line 885: invalid argument !!!
SIGABRT
See Backtrace.0 file for details
(cuda-11.7) aglnisha@scn37-mn:~/AMReX/amrex/Tests/GPU/Vector$ exit
exit

**Comment by cgilet** [comment]
This look like you're running an AMReX example and not something from IAMR. If you're still having this issue, please open an issue on the AMReX page.
