### ISSUE TITLE
IAMR Capability

### ISSUE THREAD

**Issue by AjitPanja** [AMReX-Codes/IAMR#16]
Is IAMR capable of simulating mixing of two different miscible fluid species due to density difference? Thank you in advance for your response.

**Comment by drummerdoc** [comment]
Sure!  Clearly the density ratio is going to factor in to how well this will work for you, but IAMR was developed to handle pretty significant ratios, so you should be able to push it pretty hard.

**Comment by knutsvk** [comment]
You can have a look at the 2D Rayleigh-Taylor example:
https://github.com/AMReX-Codes/IAMR/blob/master/Exec/run2d/inputs.2d.rt

-- 
Knut Sverdrup

**Comment by AjitPanja** [comment]
Thank you both for your response. In Rayleigh-Taylor instability, the two liquids are immiscible. The problem I am trying to simulate is turbulent mixing of two non-reactive miscible gases.
