### ISSUE TITLE
Questions about where to use the FORT_XVELFILL and FORT_PRESFILL in the source codes?

### ISSUE THREAD

**Issue by ruohai0925** [AMReX-Codes/IAMR#17]
Hello all,

I am struggling with the boundary conditions. I try to understand **where the source codes use the FORTRAN subroutine FORT_XVELFILL and FORT_PRESFILL.** 

Here are my thoughts.

As a lid-driven example, the physical boundary condition is non-slip and it changes to the EXT_DIR mathematical boundary condition both for normal velocity and tangential velocity.  Here https://github.com/AMReX-Codes/IAMR/blob/56efa2ce53539acf3aa3a355ced05690eba7cd02/Source/NS_setup.cpp#L186
BndryFunc(FORT_XVELFILL) is set.  The FORT_XVELFILL, in this case, is useful since the x velocity should always be 1 in the upper boundary condition along the y-direction.

Guided by my intuition, I think every time-advancing or Poisson solving, this subroutine should be used to reset the boundary velocity. But I just do not know **where and how the source code (AMReX and IAMR) use this subroutine?**

Thanks so much.

Jordan

**Comment by asalmgren** [comment]
These subroutines (FORT_XVELFILL etc) are used to fill physical boundary
conditions every time you do a FillPatch operation.

**Comment by ruihai0925** [comment]
@asalmgren Got it. I re-learned it from one of the tutorial examples so that when I write the codes, I can use the FillPatch operation.  Really interesting.

**Comment by ruihai0925** [comment]
An additional question about the FORT_PRESFILL, see here: https://github.com/AMReX-Codes/IAMR/blob/56efa2ce53539acf3aa3a355ced05690eba7cd02/Exec/run2d/PROB_2D.F#L2161

**I am confused about location of p(i,j) and p(ilo,j).** My understand is p(ilo,j) locates at the left boundary of the domain, p(i,j) locates at lefter of the left boundary. So I can understand it as a kind of simple extrapolation. But does this assignment relate to the HOMOGENEOUS NEUMANN boundary condition. If the thing is like this, it does satisfy that the normal derivative of pressure at the left boundary is 0. Not exactly understand this subroutine.

Jordan
