### ISSUE TITLE
Questions about different diffusive schemes used in IAMR

### ISSUE THREAD

**Issue by ruohai0925** [AMReX-Codes/IAMR#18]
Hello all,

I am now writing the codes about dealing with the diffusive term of the scalar equation. I noticed there are three different rho_flags in the IAMR according to the diffusion type choosing. Then based on the rho_flag, different fluxes terms will be defined and stored, such as codes in the Diffusion::diffusive_scalar. 

Now I understand the scheme in the JCP paper, but it seems too difficult for me to distinguish these three different diffusion types and their advantages. Could someone give me a general and short explanation of these three different diffusion types? What are the underlying ideas about designing them?

Thanks so much.

Jordan

**Comment by ajnonaka** [comment]
Let me chat with @asalmgren about this today - I don't know the history of what these options are.  I have a vague understanding about how this relates to whether you are diffusing a simple scalar "phi" as opposed to a conservative rho-weighted scalar "rho*phi", but there appear to be more options here than I am familiar with.

**Comment by drummerdoc** [comment]
There are three types, corresponding to three types of density weightings in the time derivative.

     rho.cp(T).DT/Dt, Dc/Dt, and D(rho.Y)/Dt

The first here will use a time-centered rho, the second doesn't have a rho (this corresponds to what is in the IAMR paper), and the time derivative in the third is discretized as 

[ (rho.Y)^{n+1} - (rho.Y)^n ]/delta

This is used, for example, in the low Mach algorithm.

**Comment by ruihai0925** [comment]
Thanks, Andy and Marc. I will go back to think and re-learn this question before adding more understandings here.
