### ISSUE TITLE
Type mismatch in 3D

### ISSUE THREAD

**Issue by WeiqunZhang** [AMReX-Codes/IAMR#2]
Function extrapproj in PROJOUTFLOWBC_F.H vs. Fortran procedure in PROJOUTFLOWBC_3D.F
    number of arguments 47 does NOT match 46.

Function filterp in PROJECTION_F.H vs. Fortran procedure in PROJECTION_3D.F
    number of arguments 15 does NOT match 12.

Function radmpy in PROJECTION_F.H vs. Fortran procedure in PROJECTION_3D.F
    number of arguments 13 does NOT match 11.
    arg #9: C type ['int', 'pointer'] does NOT match Fortran type ('REAL 8', 'pointer', 'r').
    arg #11: C type ['double', 'pointer'] does NOT match Fortran type ('INTEGER 4', 'pointer', 'n').

Function raddiv in PROJECTION_F.H vs. Fortran procedure in PROJECTION_3D.F
    number of arguments 13 does NOT match 11.
    arg #9: C type ['int', 'pointer'] does NOT match Fortran type ('REAL 8', 'pointer', 'r').
    arg #11: C type ['double', 'pointer'] does NOT match Fortran type ('INTEGER 4', 'pointer', 'n').

**Comment by drummerdoc** [comment]
This looks like something Ann did in 2D but not 3D, lazily assigning it to her... :)

**Comment by asalmgren** [comment]
Anyone care if I get rid of FILTERP?   It's a hack to start with ...

**Comment by asalmgren** [comment]
Done and done.

**Comment by WeiqunZhang** [comment]
Function extrapproj in PROJOUTFLOWBC_F.H vs. Fortran procedure in PROJOUTFLOWBC_3D.F
    number of arguments 46 does NOT match 47.
184 functions checked, 1 error(s) found.  More details can be found in tmp_build_dir/t/3d.gnu.MPI.EXE/amrex_typecheck.ou.

**Comment by WeiqunZhang** [comment]
Found by `make typecheck` in Exec/run3d.
