### ISSUE TITLE
question about velocity perturbations

### ISSUE THREAD

**Issue by JTang-HUST** [AMReX-Codes/IAMR#22]
Hello all, I am a freshman in IAMR.
Here are my small questions about velocity perturbations. I want to superimpose some velocity perturbation on inlet velocity. So I changed  one line in FORT_YVELFILL function  PROB_3D.F:
v(i,j,k) = adv_vel+vturb
which vturb is a random noise. My case always stops in the initial step with an BOXLIB ERROR: Multigrid Solve: failed to converge in max_iter iterations, even the perturbation is very small. 
Is this method  wrong or is there other way to superimpose velocity perturbation?

**Comment by asalmgren** [comment]
Hi JTang-HUST -- two questions:

1) Does the solve work ok if vturb = 0?
2) What are your boundary conditions?

**Comment by JTang-HUST** [comment]
Thanks for your reply，the boundary condition I set is inlet and if I set vturb = 0 the case can run with laminar inlet condition well.

**Comment by asalmgren** [comment]
What are the boundary conditions on the other 5 faces?

**Comment by JTang-HUST** [comment]
My case is a simple planar jet, the boundary condition set as 
ns.lo_bc  =  2 1 0
ns.hi_bc  =  2 2 0
At the lower y boundary I set the inlet boundary condition and only in central rectangular jet width adv_vel is not zero and in the other parts adv_vel is zero.

**Comment by ruihai0925** [comment]
Hello, JTang, when you say the MG solver does not converge, what the solver is? Since in IAMR, there are different codes which use different MG solvers. From my experience, the non-convergent issue happens because of non-compatibility of the boundary condition for Poisson equation.

Maybe you can show the inputs file and the error output (use ./amr3d.gnu.MPI.ex inputs > output.txt for error output in a file) so that we can see the specific error.

Best. 

Jordan

**Comment by JTang-HUST** [comment]
Thank you for your advice, ruihai0925. My inputs file is write as follows, 
max_step                = 100000
amr.n_cell              = 256 256 64- 
amr.max_level           =  0
ns.v                    =  0
amr.check_int|  |   |   =  100 
amr.plot_int|   |   |   =  100 
ns.cfl                  =  0.7--
ns.init_shrink          =  0.3-
ns.init_iter          | =  3-- 
ns.vel_visc_coef        =  1e-5
ns.scal_diff_coefs      =  0.0 
amr.probin_file |   |   =  probin.3d.jet
geometry.coord_sys   |  =  0
geometry.prob_lo     |  =  0. 0. 0.
geometry.prob_hi     |  =  0.24 0.24 0.06
geometry.is_periodic |  =  0 0 1 
ns.gravity = 0.0 
ns.lo_bc             |  =  2 1 0 
ns.hi_bc             |  =  2 2 0 

And the error and warning in output log file is, 
BOXLIB WARN: BiCGStab_SOLVE: failure 1
BOXLIB WARN: BICGSTAB_solve: breakdown in bicg, going with what I have
BOXLIB ERROR: Multigrid Solve: failed to converge in max_iter iterations

And the added part in PROB_3D file is, 
if(abs(x-jet_x).lt.jet_width) then
      v(i,j,k) = adv_vel+vturb
else
      v(i,j,k) = zero
end if

From the output log file I know the error is in the BiCGStab_SOLVE, but I am not clear why this happened even I set the vturb close to zero.
