### ISSUE TITLE
question about running IAMR on cori

### ISSUE THREAD

**Issue by burlen** [AMReX-Codes/IAMR#25]
Hi, I'm running IAMR 3d rt example on cori. I'd like to runs in the 1k - 8k cores range.

I'm seeing warnings
```
BOXLIB WARN: BiCGStab_SOLVE: failure 1
BOXLIB WARN: BICGSTAB_solve: breakdown in bicg, going with what I have
```
I've tried 256,512,1024 and 2048 MPI processes. I think I've seen these warnings in all of them. Should I be changing the input file as I use more cores?

Burlen

**Comment by drummerdoc** [comment]
Nah, unless the multigrid solvers actually fail, you can safely ignore this message.

**Comment by burlen** [comment]
OK, thanks.
