### ISSUE TITLE
Low Mach constraint options in IAMR

### ISSUE THREAD

**Issue by tobyeh** [AMReX-Codes/IAMR#26]
Hello,

I am currently developing a model of atmospheric plume rise, for which I had previously implemented conservative projection method (Almgren et al 1998) in my own code, along with a variety of low mach constraints (incomp, bous, anelastic and psuedo-incomp). I'm keen now to take advantage of AMReX and develop IAMR for this purpose. My question is: are all these constraints currently implemented in IAMR or is there only an option for incompressible at present? 
I understand that MaestroeX does have the low mach psuedo incom constraint, but not the viscous terms - i intend to keep the diffusive parts available in IAMR to develop a suitable subgrid turbulence model, so my preference is to use and modify IAMR. Thanks in advance for your help

**Comment by asalmgren** [comment]
There is also support there for anelastic but it hasn't been tested in
quite a while so may be out of date.

Ann
