### ISSUE TITLE
MOREGENGETFORCE

### ISSUE THREAD

**Issue by tobyeh** [AMReX-Codes/IAMR#27]
I've noticed a lot of pre-processor flags with GENGETFORCE and MOREGENGETFORCE. What is the difference between these? Is there a listing of the pre-proc flags and their effects anywhere (I couldn't find any in the user guide nor in comments)
Thanks

**Comment by drummerdoc** [comment]
We should clean all that out someday.  No, there isn't a formal listing of such things.  You just have to thumb through the code to see what they do.  The defines related to GETFORCE, for example, are variations on the call sequence to compute the force in the momentum equation.  We had a collaborator that needed additional state data to correctly compute the force, but he didn't want to break other people's codes.  Before we started using git, the concept of code branches was not familiar, so ifdef's were the way to support new and old versions.  Eventually, such things should be cleaned up (removed), but for now you need to just figure out what the code says they do (or ask specific questions here...).  I hope that helps.
