### ISSUE TITLE
Pressure boundary condition

### ISSUE THREAD

**Issue by nataraj2** [AMReX-Codes/IAMR#32]
Hi,

I learned from the JCP paper that describes the IAMR formulation that an outflow uses phi_MAC=0 (no tangential acceleration condition). I would like to know if IAMR does a global mass conservation correction when dealing with inflow-outflow cases.

**Comment by asalmgren** [comment]
hTe integral of the normal velocity on the outflow face is equal to the
integral of the velocity on the inflow face (assuming side walls) after the
MAC projection.  This is the velocity field that updates the density.  So
mass is conserved.   Is this what you're asking about mass conservation?
If not, could you add more detail about what you're asking?

**Comment by nataraj2** [comment]
Yes. That was the question I had. Thanks for clarifying.
