### ISSUE TITLE
Viscous terms

### ISSUE THREAD

**Issue by nataraj2** [AMReX-Codes/IAMR#33]
Does IAMR assume constant viscosity? We are looking at implementing LES models and would like to know if the viscous term is already implemented as del.(mu*del u). That would make things easier.

**Comment by asalmgren** [comment]
The default is constant viscosity but you can set ns.variable_vel_visc = 1
in the inputs file to use variable viscosity.

**Comment by nataraj2** [comment]
Thanks, Ann.
