### ISSUE TITLE
NavierStokes::velocity_diffusion_update

### ISSUE THREAD

**Issue by nataraj2** [AMReX-Codes/IAMR#35]
Hi,

I am trying to understand the code. Have a question. In the routine ```NavierStokes::velocity_diffusion_update```, if we don't have variable viscosity, then the values of ```loc_viscn``` and ``` loc_viscnp1``` are zero. And then ```diffuse_velocity_setup ``` and ```diffusion->diffuse_velocity``` get evaluated with zeroes. If we have variable viscosity then those values are non zero. Does that seem to be right?

**Comment by WeiqunZhang** [comment]
I don't think there is anything wrong.  `loc_viscn` and `loc_viscnp1` are pointers.  Being zero means they are null pointers.  They can be used for testing as a bool flag.

**Comment by nataraj2** [comment]
That's right. Got it. Thanks.
