### ISSUE TITLE
Why ScalMinMax is called in the scalar_update subroutine ? 

### ISSUE THREAD

**Issue by ruihai0925** [AMReX-Codes/IAMR#8]
Hello all,

I have a small question about godunov->ConservativeScalMinMax function in the scalar_update subroutine, the comments show this function is used to correct field to avoid undershoots or overshoots. **Could someone give more explanations about this function? (in what numerical situation, do we need this function)**

In the according Fortran subroutine,  some min and max functions are used. I am still confused why they are used. 

Thanks so much!

**Comment by drummerdoc** [comment]
Godunov methods in general can violate maxima-preservation, generating small under/over shoots, particularly in the presence of propagating discontinuities, and particularly with spatially-dependent velocity fields (as the theory is developed for constant speeds).  Often a "safety factor" is implicitly used by running at a CFL number of 0.9, say, to account for this.  While such features are often harmless, there are some applications for which these violations can crash a code (perhaps density drops below a physically-based threshold, or a mass fraction peaks above unity, say).  In these cases, one may be satisfied with advection scheme in general, but may want to guard against the code crashing, reasoning that the cases being run are non-smooth and that such "robustifications" do not have any negative impact.  

Of course, while the option is available in our codes, they must be used with great caution.  The user needs to understand the good and bad effects of such a procedure.

**Comment by ruihai0925** [comment]
Thanks Marc. I noticed the default value is 0. I will reconsider this Scale function when applying it into discontinuous water bubble problems in two phase flow.
