### ISSUE TITLE
Questions about AMR level and Multigrid level in the JCP paper

### ISSUE THREAD

**Issue by ruohai0925** [AMReX-Codes/IAMR#9]
Hello all,

Happy new year.

When reading the paper [1], I have some thoughts and confusing about AMR level and Multigrid level. 
![image](https://user-images.githubusercontent.com/30739800/34472633-e3b268ca-ef2b-11e7-9ee1-1d4143b00008.png)

**My question is why the Else if condition is needed in the pseudocode part?**  

Here is what I am thinking. If AMR level is 2, L_hi = 2, L_lo = 0. If level solver is considered, for each AMR level, multi-grid level is introduced for coarsening. We can get m(2) = 2, but generally m(0) != 0 since 0 AMR level can still be coarsen. I am not sure if I understand it right. How the m(l) is determined?

Thanks so much!

Reference:
1. Almgren, Ann S., et al. "A conservative adaptive projection method for the variable density incompressible Navier–Stokes equations." Journal of computational Physics 142.1 (1998): 1-46.

**Comment by WeiqunZhang** [comment]
The `Else if` part is for bottom multi-grid level on fine AMR levels.  Take a look at Fig. 2 of the Almgren et al. paper.  The `Else if` part is for dots between dotted lines.  Note that the figure assumes the refinement ratio is 4.  If it is 2, there is only one mutli-grid level on fine amr levels, and the `Else if` part will be run on those levels.

**Comment by ruihai0925** [comment]
@WeiqunZhang Thanks for your explanation. 

Here are some my additional understandings. The AMR levels refer to patch levels. The Multigrid level is used for solving, which can be applied to each AMR level. Hope this to be helpful to someone who is interested in their differences.
